# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d135dae25cfffcc411d3159a5cbcfa71e93cabb95e0aeb04ef956f94292667e45a0dfa6f2da023c0e6c0120a2a8762faad7b80b360b420357c7d3af21f38882

test:
  secret_key_base: 57ca338616150adcad23c0091e25e8cd9607e22b227181f228c146fb7643f069f34c7e3a24e9760c8b6e1ea1831486706df8eaea6e37acf49ec3cfcc1158bebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
